{
  "page_load": {
    "time": 0,
    "passed": false,
    "error": "HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /finances (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f73c4017510>: Failed to establish a new connection: [Errno 111] Connection refused'))"
  },
  "api_transactions": {
    "time": 0,
    "passed": false,
    "error": "HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /api/account-transactions (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f73c4020390>: Failed to establish a new connection: [Errno 111] Connection refused'))"
  }
}